import { Timestamp } from 'firebase/firestore';
import { Platform, PlatformInput } from './types';

const FALLBACK_TIMESTAMP = Timestamp.fromDate(new Date('2026-05-10T00:00:00.000Z'));

function createFallbackPlatform(id: string, input: PlatformInput): Platform {
  return {
    id,
    ...input,
    createdAt: FALLBACK_TIMESTAMP,
    updatedAt: FALLBACK_TIMESTAMP,
  };
}

export const PUBLIC_PLATFORM_FALLBACK: Platform[] = [
  createFallbackPlatform('BuKy0T3RVQQVssetsuee', {
    name: 'Lexio',
    description: 'Producao juridica com IA, com acesso por Google ou e-mail e senha.',
    category: 'Trabalho',
    accessUrl: 'https://lexio.web.app/',
    iconUrl: 'https://www.google.com/s2/favicons?sz=128&domain=lexio.web.app',
    authMethod: 'ambos',
    visible: true,
    order: 10,
  }),
  createFallbackPlatform('jaf1TLjn1idlQFlnKLa4', {
    name: 'CAOCIPP',
    description: 'Gestao inteligente de processos administrativos com autenticacao Google.',
    category: 'Trabalho',
    accessUrl: 'https://consultascao.web.app/',
    iconUrl: 'https://www.google.com/s2/favicons?sz=128&domain=consultascao.web.app',
    authMethod: 'google',
    visible: true,
    order: 20,
  }),
  createFallbackPlatform('RtJzm3ZO5749hgsoQEhr', {
    name: 'SalomoneIA',
    description: 'Workspace de IA operacional para orquestracao, handoffs e artefatos.',
    category: 'IA',
    accessUrl: 'https://salomone.web.app/',
    iconUrl: 'https://www.google.com/s2/favicons?sz=128&domain=salomone.web.app',
    authMethod: 'nenhum',
    visible: true,
    order: 30,
  }),
  createFallbackPlatform('jH7xzlnxtKQ5NFHkplT8', {
    name: 'Nexus',
    description: 'Workspace de audio com IA para gravar, transcrever e organizar ideias.',
    category: 'IA',
    accessUrl: 'https://anotes.web.app/',
    iconUrl: 'https://www.google.com/s2/favicons?sz=128&domain=anotes.web.app',
    authMethod: 'google',
    visible: true,
    order: 40,
  }),
  createFallbackPlatform('Y3ObTJtSRpzQrLVIfV07', {
    name: 'Protagonista RPG',
    description: 'Plataforma Fate Core para criar personagens, gerenciar campanhas e jogar online.',
    category: 'RPG',
    accessUrl: 'https://protagonistarpg.com.br/',
    iconUrl: 'https://www.google.com/s2/favicons?sz=128&domain=protagonistarpg.com.br',
    authMethod: 'ambos',
    visible: true,
    order: 50,
  }),
  createFallbackPlatform('V45767nvUKhPcYCwS8lR', {
    name: 'OmniMesa',
    description: 'Mesa virtual e ambiente de testes da OmniMesa com login Google.',
    category: 'RPG',
    accessUrl: 'https://protagonistarpg.com.br/omnivtt/',
    iconUrl: 'https://www.google.com/s2/favicons?sz=128&domain=protagonistarpg.com.br',
    authMethod: 'google',
    visible: true,
    order: 60,
  }),
  createFallbackPlatform('wliBJ71kLKxVsy1xNOq0', {
    name: 'OmniForge RPG',
    description: 'Gerador de campanhas de RPG com IA para criar sessoes, NPCs, encontros e narrativas.',
    category: 'RPG',
    accessUrl: 'https://www.protagonistarpg.com.br/omniforge/',
    iconUrl: 'https://www.google.com/s2/favicons?sz=128&domain=protagonistarpg.com.br',
    authMethod: 'google',
    visible: true,
    order: 70,
  }),
  createFallbackPlatform('omnidice', {
    name: 'OmniDice',
    description: 'Rolador profissional de dados 3D para RPG, com fisica realista e suporte de streaming para OBS.',
    category: 'RPG',
    accessUrl: 'https://omnidice.protagonistarpg.com.br/',
    iconUrl: 'https://www.google.com/s2/favicons?sz=128&domain=omnidice.protagonistarpg.com.br',
    authMethod: 'nenhum',
    visible: true,
    order: 75,
  }),
  createFallbackPlatform('e0o0F3F4KGGzBfoMhH8h', {
    name: 'Super Bolao',
    description: 'Bolao da Copa 2026 com ranking, palpites e entrada com Google.',
    category: 'Jogos',
    accessUrl: 'https://superbolao.web.app/',
    iconUrl: 'https://www.google.com/s2/favicons?sz=128&domain=superbolao.web.app',
    authMethod: 'google',
    visible: true,
    order: 80,
  }),
  createFallbackPlatform('RWQuD76pCPLkovPiCidB', {
    name: 'Laura',
    description: 'Jogo educacional infantil com experiencia interativa e area dedicada aos pais.',
    category: 'Jogos',
    accessUrl: 'https://fsalamoni.github.io/Laura/',
    iconUrl: 'https://www.google.com/s2/favicons?sz=128&domain=fsalamoni.github.io',
    authMethod: 'nenhum',
    visible: true,
    order: 90,
  }),
  createFallbackPlatform('mdzkYwUPNy8fzsrkfleK', {
    name: 'Psico SaaS',
    description: 'Plataforma de acompanhamento emocional com diario, insights e suporte por IA.',
    category: 'Outros',
    accessUrl: 'https://fsalamoni.github.io/Psico-/',
    iconUrl: 'https://www.google.com/s2/favicons?sz=128&domain=fsalamoni.github.io',
    authMethod: 'email',
    visible: true,
    order: 100,
  }),
].sort((left, right) => left.order - right.order);